djangoplatform/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('pricing/', views.pricing, name='pricing'),
    path('users/', views.users, name='users'),
    path('user_add/', views.user_add, name='user_add'),
    path('teachers/', views.teachers, name='teachers'),
    path('courses/', views.courses, name='courses'),
    path('course_add/', views.course_add, name='course_add'),
    path('course_edit/<int:course_id>/', views.course_edit, name='course_edit'),
    path('course_delete/<int:course_id>/', views.course_delete, name='course_delete'),
    path('course_detail/<int:course_id>/', views.course_detail, name='course_detail'),
    path('not_found/', views.not_found, name='not_found'),
    path('teacher_edit/<int:teacher_id>/', views.teacher_edit, name='teacher_edit'),
    path('teacher_delete/<int:teacher_id>/', views.teacher_delete, name='teacher_delete'),
    path('teacher_detail/<int:teacher_id>/', views.teacher_detail, name='teacher_detail'),
    path('teacher_add/', views.teacher_add, name='teacher_add'),
    path('students/', views.students, name='students'),
    path('student_add/', views.student_add, name='student_add'),
    path('student_edit/<int:student_id>/', views.student_edit, name='student_edit'),
    path('student_delete/<int:student_id>/', views.student_delete, name='student_delete'),
    path('student_detail/<int:student_id>/', views.student_detail, name='student_detail'),
    
]
 

account/models.py
from django.db import models
from datetime import datetime
from khayyam import JalaliDate
from persiantools import digits

# Create your models here.


class Teacher(models.Model):
    class Meta:
        verbose_name = 'استاد'
        verbose_name_plural = 'استاد'
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE, verbose_name='کاربر')
    phone = models.CharField(max_length=11, verbose_name='شماره تلفن')
    date_of_birth = models.DateField('تاریخ تولد')
    address = models.CharField('آدرس', max_length=200)
    join_date = models.DateField('تاریخ عضویت', auto_now_add=True)
    
    degree_choices = (
        ('دیپلم', 'دیپلم'),
        ('فوق دیپلم', 'فوق دیپلم'),
        ('لیسانس', 'لیسانس'),
        ('فوق لیسانس', 'فوق لیسانس'),
        ('دکتری', 'دکتری'),
    )
    degree = models.CharField('مدرک', max_length=10, choices=degree_choices)

    def get_full_name(self):
        return self.user.first_name + ' ' + self.user.last_name

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

    def jjoin_date(self):
        return digits.en_to_fa(JalaliDate(self.join_date).strftime('%A %d %B %Y'))
    
    def jdate_of_birth(self):
        return digits.en_to_fa(JalaliDate(self.date_of_birth).strftime('%A %d %B %Y'))

class Course(models.Model):
    class Meta:
        verbose_name = 'دوره'
        verbose_name_plural = 'دوره '
    name = models.CharField(max_length=50, verbose_name='نام دوره')
    start_date = models.DateField('تاریخ شروع')
    end_date = models.DateField('تاریخ پایان')
    length = models.IntegerField(verbose_name='طول دوره')
    teacher = models.ForeignKey(Teacher, on_delete=models.PROTECT, verbose_name='استاد')
    status_choices = (
        ('1', 'در حال برگزاری'),
        ('2', 'برگزار شده'),
        ('3', 'پایان داده شده'),
    )
    status = models.CharField(max_length=1, choices=status_choices, verbose_name='وضعیت')

    def get_time_difference_in_days(self):
        return (self.end_date - self.start_date).days
    
    def get_time_untill_now_in_days(self):
        return (datetime.now().date() - self.start_date).days

    def jstart_date(self):
        return digits.en_to_fa(JalaliDate(self.start_date).strftime('%A %d %B %Y'))
    def jend_date(self):
        return digits.en_to_fa(JalaliDate(self.end_date).strftime('%A %d %B %Y'))
    
    def __str__(self):
        return self.name

class Student(models.Model):
    class Meta:
        verbose_name = 'دانشجو'
        verbose_name_plural = 'دانشجو'
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE, related_name='student', verbose_name='کاربر')
    phone = models.CharField(max_length=11, verbose_name='شماره تلفن')
    date_of_birth = models.DateField('تاریخ تولد')
    address = models.CharField('آدرس', max_length=200)
    join_date = models.DateField('تاریخ عضویت', auto_now_add=True)
    courses = models.ManyToManyField(Course, verbose_name='دوره ها')
    degree_choices = (
        ('دیپلم', 'دیپلم'),
        ('فوق دیپلم', 'فوق دیپلم'),
        ('لیسانس', 'لیسانس'),
        ('فوق لیسانس', 'فوق لیسانس'),
        ('دکتری', 'دکتری'),
    )
    degree = models.CharField('مدرک', max_length=10, choices=degree_choices)

    def get_full_name(self):
        return self.user.first_name + ' ' + self.user.last_name

    def jdate_of_birth(self):
        return digits.en_to_fa(JalaliDate(self.date_of_birth).strftime('%A %d %B %Y'))

    def jjoin_date(self):
        return digits.en_to_fa(JalaliDate(self.join_date).strftime('%A %d %B %Y'))

    def __str__(self):
        return self.usser.first_name + ' ' + self.usser.last_name



class Mark(models.Model):
    class Meta:
        verbose_name = 'نمره'
        verbose_name_plural = 'نمره'
    student = models.ForeignKey(Student, on_delete=models.PROTECT, verbose_name='دانشجو')
    course = models.ForeignKey(Course, on_delete=models.PROTECT, verbose_name='دوره')
    mark = models.IntegerField('نمره')

    def __str__(self):
        return self.student.name + ' ' + self.course.name



class Homework(models.Model):
    class Meta:
        verbose_name = 'آزمون'
        verbose_name_plural = 'آزمون'
    course = models.ForeignKey(Course, on_delete=models.PROTECT, verbose_name='دوره')
    title = models.CharField(max_length=50, verbose_name='عنوان')
    description = models.TextField(verbose_name='توضیحات')
    deadline = models.DateField(verbose_name='زمان تحویل')
    upload_time = models.DateField(verbose_name='زمان آپلود', auto_now_add=True)
    upload_file = models.FileField(verbose_name='فایل آپلود شده', upload_to='homework/')

    def __str__(self):
        return self.title

    def jdeadline(self):
        return digits.en_to_fa(JalaliDate(self.deadline).strftime('%A %d %B %Y'))

class Answer(models.Model):
    class Meta:
        verbose_name = 'پاسخ'
        verbose_name_plural = 'پاسخ'
    homework = models.ForeignKey(Homework, on_delete=models.PROTECT, verbose_name='آزمون')
    student = models.ForeignKey(Student, on_delete=models.PROTECT, verbose_name='دانشجو')
    answer = models.FileField(verbose_name='پاسخ دانشجو', upload_to='answer/')

    def __str__(self):
        return self.student.name + ' ' + self.homework.title

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, authenticate, login as auth_login
from django.contrib.auth.models import User, Group
from account.forms import CustomUserForm, TeacherForm, CourseForm, StudentForm, TeacherEditForm, CustomUserFormTeacher, CustomUserFormStudent
from django.contrib import messages
from account.models import Student, Teacher, Course, Mark
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from persiantools.jdatetime import JalaliDate
# Create your views here.

def index(request):
    user = request.user
    marks = []
    students = []
    teachers = []
    courses = []
    if user.is_authenticated:
        if user.groups.filter(name='admin').exists():
            user_role = 'admin'
            courses = Course.objects.all()
            students = Student.objects.all()
            teachers = Teacher.objects.all()
        elif user.groups.filter(name='teacher').exists():
            user_role = 'teacher'
            courses = Course.objects.filter(teacher=user.teacher).all()
        elif user.groups.filter(name='student').exists():
            user_role = 'student'
            courses = Student.objects.get(user=user).courses.all()
            marks = Mark.objects.filter(student=Student.objects.get(user=user))
        
        
        return render(request, 'main/index.html', {'courses': courses, 'marks': marks, 'students': students, 'teachers': teachers, 'user_role': user_role})
    return redirect('account:login')



def pricing(request):
    return render(request, 'main/pricing.html')

@login_required
def users(request):
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        users = User.objects.all()
        return render(request, 'main/users.html', {'users': users, 'user_role': user_role})
    else:
        return redirect('main:not_found')

@login_required
def teachers(request):
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        teachers = Teacher.objects.all()
        return render(request, 'main/teachers.html', {'teachers': teachers, 'user_role': user_role})
    else:
        return redirect('main:not_found')

@login_required
def students(request):
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        students = Student.objects.all()
        return render(request, 'main/students.html', {'students': students, 'user_role': user_role})
    else:
        return redirect('main:not_found')


@login_required
def courses(request):
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        courses = Course.objects.all()
        return render(request, 'main/courses.html', {'courses': courses, 'user_role': user_role})
    else:
        return redirect('main:not_found')

def not_found(request):
    return render(request, 'main/404.html')

@login_required
def teacher_edit(request, teacher_id):
    teacher = Teacher.objects.get(id=teacher_id)
    form = TeacherEditForm(request.POST or None, initial={'address': teacher.address, 'phone': teacher.phone, 'degree': teacher.degree})
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        if request.method == 'POST':
            if form.is_valid():
                teacher.phone = form.cleaned_data['phone']
                teacher.address = form.cleaned_data['address']
                teacher.degree = form.cleaned_data['degree']
                teacher.save()
                return redirect('main:teachers')
        return render(request, 'main/teacher_edit.html', {'teacher': teacher, 'user_role': user_role, 'form': form})
    else:
        return redirect('main:not_found')

@login_required
def teacher_delete(request, teacher_id):
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        teacher = Teacher.objects.get(id=teacher_id)
        teacher.delete()
        teacher.save()
        return redirect('main:teachers')
    else:
        return redirect('main:not_found')

@login_required
def teacher_add(request):
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        form1 = CustomUserFormTeacher(request.POST or None)
        form2 = TeacherForm(request.POST or None)
        if request.method == 'POST':
            if form1.is_valid():
                new_user = form1.save()
                new_user.save()
                new_user.groups.add(Group.objects.get(name='teacher'))
                messages.success(request, 'حساب کاربری با موفقیت ایجاد شد')
                if form2.is_valid():
                    new_teacher = Teacher.objects.create(user = new_user, phone=form2.cleaned_data['phone'], date_of_birth=JalaliDate(form2.cleaned_data['date_of_birth'].year, form2.cleaned_data['date_of_birth'].month, form2.cleaned_data['date_of_birth'].day ).to_gregorian(), address=form2.cleaned_data['address'], degree=form2.cleaned_data['degree'])
                    new_teacher.save()
                    messages.success(request, 'استاد جدید با موفقیت ایجاد شد')
                    return redirect('main:teachers')
        return render(request, 'main/teacher_add.html', {'form1': form1, 'form2':form2, 'user_role': user_role})
    else:
        return redirect('main:not_found')

def user_add(request):
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        form = CustomUserForm(request.POST or None)
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                user = User.objects.get(username=form.cleaned_data['username'])
                user.groups.add(Group.objects.get(name=form.cleaned_data['role']))
                user.save()
                messages.success(request, 'حساب کاربری جدید با موفقیت ایجاد شد')
                return redirect('main:users')
        return render(request, 'main/user_add.html', {'form': form, 'user_role': user_role})
    else:
        return redirect('main:not_found')

@login_required
def course_add(request):
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        form = CourseForm(request.POST or None)
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                messages.success(request, 'درس جدید با موفقیت افزوده شد')
                return redirect('main:courses')
        return render(request, 'main/course_add.html', {'form': form, 'user_role': user_role})
    else:
        return redirect('main:not_found')

@login_required
def course_edit(request, course_id):
    course = Course.objects.get(id=course_id)
    form = CourseForm(request.POST or None, initial={'name': course.name, 'length': course.length, 'teacher': course.teacher, 'status': course.status})
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        if request.method == 'POST':
            if form.is_valid():
                course.name = form.cleaned_data['name']
                course.start_date = JalaliDate(form.cleaned_data['start_date'].year, form.cleaned_data['start_date'].month, form.cleaned_data['start_date'].day ).to_gregorian()
                course.end_date = JalaliDate(form.cleaned_data['end_date'].year, form.cleaned_data['end_date'].month, form.cleaned_data['end_date'].day ).to_gregorian()
                course.length = form.cleaned_data['length']
                course.teacher = form.cleaned_data['teacher']
                course.status = form.cleaned_data['status']
                course.save()
                return redirect('main:courses')
        return render(request, 'main/course_edit.html', {'course': course, 'user_role': user_role, 'form': form})
    else:
        return redirect('main:not_found')

@login_required
def course_delete(request, course_id):
    if request.user.groups.filter(name='admin').exists():
        course = get_object_or_404(Course, id=course_id)
        course.delete()
        return redirect('main:courses')
    else:
        return redirect('main:not_found')


@login_required
def student_edit(request, student_id):
    student = Student.objects.get(id=student_id)
    form = StudentForm(request.POST or None, initial={'name': student.user.get_full_name, 'email': student.user.email, 'phone': student.phone, 'date_of_birth': JalaliDate.to_jalali(student.date_of_birth.year, student.date_of_birth.month, student.date_of_birth.day), 'courses': student.courses.all(), 'address': student.address, 'degree': student.degree})
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        if request.method == 'POST':
            if form.is_valid():
                student.phone = form.cleaned_data['phone']
                student.address = form.cleaned_data['address']
                student.courses.set(form.cleaned_data['courses'])
                student.degree = form.cleaned_data['degree']
                student.save()
                return redirect('main:students')
        return render(request, 'main/student_edit.html', {'student': student, 'user_role': user_role, 'form': form})
    else:
        return redirect('main:not_found')

@login_required
def student_delete(request, student_id):
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        student = student.objects.get(id=student_id)
        student.delete()
        student.save()
        return redirect('main:students')
    else:
        return redirect('main:not_found')

@login_required
def student_add(request):
    if request.user.groups.filter(name='admin').exists():
        user_role = 'admin'
        form1 = CustomUserFormStudent(request.POST or None)
        form2 = StudentForm(request.POST or None)
        if request.method == 'POST':
            if form1.is_valid():

main/templates/main/courses.html
{% extends 'main/layout.html' %}
{% block title %}
مدیریت دوره‌ها
{% endblock %}
{% block content %}
                <div class="container-fluid">

                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">لیست دوره‌ها</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>نام دوره</th>
                                            <th>طول دوره (جلسه) </th>
                                            <th>استاد</th>
                                            <th>وضعیت</th>
                                            <th>عملیات</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>نام دوره</th>
                                            <th>طول دوره </th>
                                            <th>استاد</th>
                                            <th>وضعیت</th>
                                            <th>عملیات</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for course in courses %}
                                        <tr>
                                            <td>{{ course.name }}</td>
                                            <td>{{ course.length }}</td>
                                            <td>{{ course.teacher }}</td>
                                            <td>{{ course.get_status_display }}</td>
                                            <td>
                                                <a href="{% url 'main:course_edit' course_id=course.id %}" class="btn btn-primary">ویرایش</a>
                                                <a href="{% url 'main:course_delete' course_id=course.id %}" class="btn btn-danger" onclick="return confirm('آیا مطمئن هستید؟')">حذف</a>
                                            </td>
                                        </tr>
                                        
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <a href="{% url 'main:course_add' %}" class="btn btn-success">افزودن دوره</a>
                        </div>
                    </div>

                </div>

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
        {% endblock %}

main/templates/main/student_add.html
{% extends 'main/layout.html' %}
{% block title %}
افزودن دانشجو 
{% endblock %}
{% block content %}
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header text-center">افزودن دانشجوی جدید </h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 m-auto">
                    <form action="{% url 'main:student_add' %}" method="post">
                        {% csrf_token %}
                    {{form1.as_p}}
                    {{form2.as_p}}
                    <input type="submit" value="افزودن" class="btn btn-primary">
                    </form>
                </div>
            </div>
                </div>
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
        {% endblock %}

main/templates/main/student_edit.html
{% extends 'main/layout.html' %}
{% block title %}
مدیریت دانشجویان
{% endblock %}
{% block content %}
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header text-center">ویرایش اطلاعات دانشجو </h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 m-auto">
                    <form action="{% url 'main:student_edit' student_id=student.id %}" method="post">
                        {% csrf_token %}
                    {{form.as_p}}
                    <input type="hidden" name="id" value="{{student.id}}">
                    <input type="submit" value="ویرایش" class="btn btn-primary">
                    <a href="{% url 'main:students' %}" class="btn btn-danger">بازگشت</a>
                    </form>
                </div>
            </div>
                </div>
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
        {% endblock %}

main/templates/main/students.html
{% extends 'main/layout.html' %}
{% load jalali_tags %}
{% block title %}
مدیریت دانشجویان
{% endblock %}
{% block content %}
                <div class="container-fluid">

                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">لیست دانشجویان</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>نام</th>
                                            <th>تلفن </th>
                                            <th>ایمیل</th>
                                            <th>تاریخ ورود </th>
                                            <th>عملیات</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>نام</th>
                                            <th>تلفن </th>
                                            <th>ایمیل</th>
                                            <th>تاریخ ورود </th>
                                            <th>عملیات</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for student in students %}
                                        <tr>
                                            <td><a href="{% url 'main:student_detail' student_id=student.id %}" >{{ student.user.first_name }} {{student.user.last_name}}</a></td>
                                            <td>{{ student.phone }}</td>
                                            <td>{{ student.user.email }}</td>
                                            <td>{{ student.jjoin_date }}</td>
                                            <td>
                                                <a href="{% url 'main:student_edit' student_id=student.id %}" class="btn btn-primary">ویرایش</a>
                                                <a class="btn btn-danger" href="{% url 'main:student_delete' student_id=student.id %}" onclick="return confirm('آیا مطمئن هستید؟')">حذف</a>
                                            </td>
                                        </tr>
                                        
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <a href="{% url 'main:student_add' %}" class="btn btn-success">افزودن دانشجو</a>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            
            <!-- End of Main Content -->

            <!-- Footer -->
        {% endblock %}

main/templates/main/teacher_edit.html
{% extends 'main/layout.html' %}
{% block title %}
مدیریت کاربران
{% endblock %}
{% block content %}
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header text-center">ویرایش اطلاعات استاد </h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 m-auto">
                    <form action="{% url 'main:teacher_edit' teacher_id=teacher.id %}" method="post">
                        {% csrf_token %}
                    {{form.as_p}}
                    <input type="hidden" name="id" value="{{teacher.id}}">
                    <input type="submit" value="ویرایش" class="btn btn-primary">
                    <a href="{% url 'main:teachers' %}" class="btn btn-danger">بازگشت</a>
                    </form>
                </div>
            </div>
                </div>
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
        {% endblock %}

main/templates/main/user_add.html
{% extends 'main/layout.html' %}
{% block title %}
افزودن کاربر 
{% endblock %}
{% block content %}
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header text-center">افزودن کاربر جدید </h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 m-auto">
                    <form action="{% url 'main:user_add' %}" method="post">
                        {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="افزودن" class="btn btn-success">
                    </form>
                </div>
            </div>
                </div>
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
        {% endblock %}

main/templates/main/users.html
{% extends 'main/layout.html' %}
{% block title %}
مدیریت کاربران
{% endblock %}
{% block content %}
                <div class="container-fluid">

                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">لیست کاربران</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>نام</th>
                                            <th>نام خانوادگی</th>
                                            <th>ایمیل</th>
                                            <th>سمت</th>
                                            <th>نام کاربری</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>نام</th>
                                            <th>نام خانوادگی</th>
                                            <th>ایمیل</th>
                                            <th>سمت</th>
                                            <th>نام کاربری</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for user in users %}
                                        <tr>
                                            <td>{{ user.first_name }}</td>
                                            <td>{{ user.last_name }}</td>
                                            <td>{{ user.email }}</td>
                                            <td>{{ user.groups.all.first }}</td>
                                            <td>{{ user.username }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <a href="{% url 'main:user_add' %}" class="btn btn-success">افزودن کاربر جدید</a>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
        {% endblock %}